version: '1.0'
services:
  schdeule_maker:
    container_name: schdeule_maker
    build: 
      dockerfile: Dockerfile
    ports:
      - 8090:8080
  db:
    image: mysql:5.7.37
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: schdeule-maker
    ports:
      - 3330:3306